### ISSUE TITLE
Unable to use glossary on Weblate

### ISSUE THREAD

**Issue by rffontenelle** [mike-fabian/ibus-table#59] opened 2021-03-07 01:31 UTC
The [ibus-table project in Weblate](https://translate.fedoraproject.org/projects/ibus-table/) has a `ibus-table` component marked as "Glossary", but the component `app` component doesn't seem to be able to use it. For some reason, when I'm adding an entry to the glossary, nothing is listed in the glossary drop-down menu.

Here is what I see when trying to add an entry (Glossário = Glossary):
![ibus-table](https://user-images.githubusercontent.com/1571783/110226140-74ebbf80-7ecb-11eb-9373-45f00149095e.png)

**Comment by mike-fabian** [comment] 2021-05-04 07:05
I didn’t notice that component until now.

The documentation:

https://docs.weblate.org/en/latest/user/glossary.html

says: “An empty glossary for a given project is automatically created with the project. ”

I tried to add something to the Portuguese glossary for ibus-table, and for me it looks like this:

![Screenshot](https://user-images.githubusercontent.com/2330175/116970192-cfc94980-acb7-11eb-9caa-1a4f02b1e3ab.png)

(In Firefox on my laptop).

**Comment by mike-fabian** [comment] 2021-05-04 07:12
I clicked on "Add" and apparently it was saved successfully. When I now go to the Portuguese translations of ibus-table and search for strings containing “preedit”, I see the relevant Glossary entry at the top right: 
![Screenshot](https://user-images.githubusercontent.com/2330175/116970738-cc828d80-acb8-11eb-8389-a7d19277fc05.png)

**Comment by mike-fabian** [comment] 2021-05-04 07:14
In the above Screenshot, I clicked on “+ Add term to glossary” and finally found the dialog shown in your screenshot.

Now it has “-------” and “ibus-table” in the combobox.

I wonder whether that has changed because I added one glossary entry ...

**Comment by mike-fabian** [comment] 2021-05-04 07:29
Maybe the “ibus-table” in the combobox appeared because I added the first term to the glossary using the start page of the project. Because I tried to reproduce this with ibus-typing-booster now which still has a completely empty glossary.
The start page of the project https://translate.fedoraproject.org/projects/ibus-typing-booster/ looks like this:

![Screenshot](https://user-images.githubusercontent.com/2330175/116972049-c392bb80-acba-11eb-8575-6a6a826d9353.png)

Now I did not click on the Glossary line there and did not add a glossary item there like I did for Portuguese. But I clicked on the “app” line and tried to add a glossary entry there. Then I got this:

![Screenshot](https://user-images.githubusercontent.com/2330175/116972326-2421f880-acbb-11eb-94d6-6ca0a50b7e05.png)

This looks like in your screenshot, the combobox is empty.

**Comment by mike-fabian** [comment] 2021-05-04 07:34
And I cannot add anything to the glossary there.

This seems to have been caused by a bug in Weblate. But it seems to work now.

**Comment by mike-fabian** [comment] 2021-05-04 07:36
Closing, because it seems to work now.

**Closed by mike-fabian** 2021-05-04 07:36 UTC

**Comment by rffontenelle** [comment] 2021-05-04 11:39
Yep, I confirm it is working. Thanks!
