### ISSUE TITLE
ctrl + shift + e issue

### ISSUE THREAD

**Issue by nabychan** [mike-fabian/ibus-table#110] opened 2022-03-12 16:17 UTC
When i press `ctrl + shift + e` in some input area, then it will stuck. Like below:     
![screenshot](https://postimg.cc/cgKmFGVP)    
through `esc`, it can be fixed, but if you leave it there and switch to other apps, you will be stuck.

**Comment by nabychan** [comment] 2022-03-12 16:18
I am running ubuntu 20.04, IBus Table version is 1.9.25, IM is WuBi-JiDian-86-JiShuag-6.0

**Comment by mike-fabian** [comment] 2022-04-04 08:41
I cannot reproduce it with ibus-table-1.16.7-1.fc35.noarch on Fedora 35.

 IBus Table version is 1.9.25 is pretty old.

I fixed some problems with the handling of shift keys recently which might have an effect on the problem you experience as well.

Can you please try whether upgrading to ibus-table-1.16.7 fixes the problem for you?

**Comment by mike-fabian** [comment] 2022-05-02 17:40
Ping 🏓

**Comment by mike-fabian** [comment] 2022-06-08 09:17
Does the problem still exist for you? As I cannot reproduce it with a current version of ibus-table, I am tempted to close this issue...

**Comment by nabychan** [comment] 2022-06-11 19:13
I'll test it within several days.

**Comment by mike-fabian** [comment] 2022-07-01 07:24
Did you have a chance to test it?

**Comment by nabychan** [comment] 2022-07-03 16:19
I don't know how to upgrade ibus-table in ubuntu 20.04. Can you give me some advise please. Thanks.

**Comment by mike-fabian** [comment] 2022-07-04 11:14
You could build from source as described here:  
http://mike-fabian.github.io/ibus-table/development.html

**Comment by nabychan** [comment] 2022-07-06 15:50
> You could build from source as described here: http://mike-fabian.github.io/ibus-table/development.html

Thanks, I'll try it

**Comment by nabychan** [comment] 2022-07-12 12:37
not work. ![1.16.9](https://s3.bmp.ovh/imgs/2022/07/12/3e09f6210e42e4c2.png)

**Comment by nabychan** [comment] 2022-07-12 13:03
Maybe it is caused by ibus-extension-gtk3. After `ctrl + shift + e`, then I press `whitespace`  ibus-extension-gtk3 application shows.

**Comment by mike-fabian** [comment] 2022-07-12 14:42
Which version of ibus do you have? 
If you are not using a gnome desktop, is `ctrl + shift + e` set to something in ibus-setup?

Currently the ibus-setup tool looks like this in ibus-1.5.26:

![Screenshot](https://user-images.githubusercontent.com/2330175/178516980-4a3822c7-a7a7-4f30-a57b-b1fdd8f64ebc.png)

The emoji input is set to `<Control>period; <Control> semicolon` by default and the Unicode code point input to `<Control><Shift>u`.

But the emoji input used to be set to `<Control><Shift>e`!

Maybe that causes your problem??

**Comment by mike-fabian** [comment] 2022-07-12 14:47
Here is a video using ibus-1.5.26 on Gnome Xorg in Fedora  36.

In the video I trigger the emoji input with `<Control> semicolon`. Then one sees a lowercase `e` underlined in the preedit.
Maybe that is what you get with `<Control><Shift>e`??

When that lowercase, underlined e shows in the preedit, one can type emoji by typng their names as seen in the video.

To get out of that emoji input mode, press Escape.

https://user-images.githubusercontent.com/2330175/178517967-43a85b0f-0437-4fcc-ab88-c8529b7fc254.mp4

**Comment by nabychan** [comment] 2022-07-12 15:39
Yes, it bahaves like in your video when I add a English input method and switch to it. And I can see a `<Control><Shift>e` setting in `ibus-setup`. 
Maybe this is problem or not of ibus. When it is not english input method, you cannot input a 😃 by `<Control><Shift>esmile<WhiteSpace>`. And when you press `<Control><Shift>e` and then point you cursor to another input box, you get a stuck `e` without preedit indication and cannot input charactors until you press `escape`.
Thanks for help.

**Comment by mike-fabian** [comment] 2022-07-12 17:17
> Yes, it bahaves like in your video when I add a English input method and switch to it. And I can see a `<Control><Shift>e` setting in `ibus-setup`.

Than you can change the setting there or remove it if you do not need it.

> Maybe this is problem or not of ibus. When it is not english input method, you cannot input a smiley by `<Control><Shift>esmile<WhiteSpace>`.

You can still use that when using ibus-table when ibus-table is in English, not in Chinese mode.

> And when you press `<Control><Shift>e` and then point you cursor to another input box, you get a stuck `e` without preedit indication and cannot input charactors until you press `escape`. Thanks for help.

I think that is an ibus bug. ibus should probably cancel the `e` in preedit when the focus goes elsewhere.

Right now I am using ibus-1.5.26 on Fedora 36 and when I move the focus the `e` gets committed. I.e. the underline disappears and it is not “stuck”, I can continue typing, but I have an extra `e` there which I don’t want and have to delete for example with Backspace.

**Comment by mike-fabian** [comment] 2022-07-14 08:26
> When it is not english input method, you cannot input a smiley by `<Control><Shift>esmile<WhiteSpace>`.

Actually you can, I knew that it works with the Japanese input method ibus-anthy but when I tried with WuBi-JiDian-86-JiShuag-6.0 (which you use), I failed and didn’t understand why.

The reason I failed was that I had only `<Control> period; <Control> semicolon` in ibus-setup as the “Emoji annotation“ trigger keys and these keybindings are used by ibus-table already, the default key bindings of ibus-table contain:

```
switch_to_next_chinese_mode ['Control+semicolon']
toggle_punctuation_mode     ['Control+period']
```

So I added `<Control> <Shift> e` back in `ibus-setup` and did choose “Chinese” for the emoji-annotation language.

Now I can use this ibus way to input emoji even with WuBi-JiDian-86-JiShuag-6.0, see this video:



https://user-images.githubusercontent.com/2330175/178937675-e98eab1a-00d6-4cc9-bce6-bba4125f447d.mp4

**Comment by nabychan** [comment] 2022-07-14 13:26
🤣Yes, It works. Thanks very much.

**Comment by mike-fabian** [comment] 2022-07-14 14:50
Is there anything left to do here or can we close this issue?

**Closed** 2022-07-14 17:29 UTC
